export const countries = [
	{ key: 'AFGHANISTAN', value: 'Afghanistan' },
	{ key: 'ALBANIA', value: 'Albania' },
	{ key: 'ALGERIA', value: 'Algeria' },
	{ key: 'ANDORRA', value: 'Andorra' },
	{ key: 'ANGOLA', value: 'Angola' },
	{ key: 'ANTIGUA_AND_BARBUDA', value: 'Antigua and Barbuda' },
	{ key: 'ARGENTINA', value: 'Argentina' },
	{ key: 'ARMENIA', value: 'Armenia' },
	{ key: 'AUSTRALIA', value: 'Australia' },
	{ key: 'AUSTRIA', value: 'Austria' },
	{ key: 'AZERBAIJAN', value: 'Azerbaijan' },
	{ key: 'THE_BAHAMAS', value: 'The Bahamas' },
	{ key: 'BAHRAIN', value: 'Bahrain' },
	{ key: 'BANGLADESH', value: 'Bangladesh' },
	{ key: 'BARBADOS', value: 'Barbados' },
	{ key: 'BELARUS', value: 'Belarus' },
	{ key: 'BELGIUM', value: 'Belgium' },
	{ key: 'BELIZE', value: 'Belize' },
	{ key: 'BENIN', value: 'Benin' },
	{ key: 'BHUTAN', value: 'Bhutan' },
	{ key: 'BOLIVIA', value: 'Bolivia' },
	{ key: 'BOSNIA_AND_HERZEGOVINA', value: 'Bosnia and Herzegovina' },
	{ key: 'BOTSWANA', value: 'Botswana' },
	{ key: 'BRAZIL', value: 'Brazil' },
	{ key: 'BRUNEI', value: 'Brunei' },
	{ key: 'BULGARIA', value: 'Bulgaria' },
	{ key: 'BURKINA_FASO', value: 'Burkina Faso' },
	{ key: 'BURUNDI', value: 'Burundi' },
	{ key: 'CAMBODIA', value: 'Cambodia' },
	{ key: 'CAMEROON', value: 'Cameroon' },
	{ key: 'CANADA', value: 'Canada' },
	{ key: 'CAPE_VERDE', value: 'Cape Verde' },
	{ key: 'CENTRAL_AFRICAN_REPUBLIC', value: 'Central African Republic' },
	{ key: 'CHAD', value: 'Chad' },
	{ key: 'CHILE', value: 'Chile' },
	{ key: 'CHINA', value: 'China' },
	{ key: 'COLOMBIA', value: 'Colombia' },
	{ key: 'COMOROS', value: 'Comoros' },
	{ key: 'CONGO,_REPUBLIC_OF_THE', value: 'Congo, Republic of the' },
	{ key: 'CONGO,_DEMOCRATIC_REPUBLIC_OF_THE', value: 'Congo, Democratic Republic of the' },
	{ key: 'COSTA_RICA', value: 'Costa Rica' },
	{ key: "COTE_D'IVOIRE", value: `Cote d'Ivoire` },
	{ key: 'CROATIA', value: 'Croatia' },
	{ key: 'CUBA', value: 'Cuba' },
	{ key: 'CYPRUS', value: 'Cyprus' },
	{ key: 'CZECH_REPUBLIC', value: 'Czech Republic' },
	{ key: 'DENMARK', value: 'Denmark' },
	{ key: 'DJIBOUTI', value: 'Djibouti' },
	{ key: 'DOMINICA', value: 'Dominica' },
	{ key: 'DOMINICAN_REPUBLIC', value: 'Dominican Republic' },
	{ key: 'EAST_TIMOR_(TIMOR-LESTE)', value: 'East Timor (Timor-Leste)' },
	{ key: 'ECUADOR', value: 'Ecuador' },
	{ key: 'EGYPT', value: 'Egypt' },
	{ key: 'EL_SALVADOR', value: 'El Salvador' },
	{ key: 'EQUATORIAL_GUINEA', value: 'Equatorial Guinea' },
	{ key: 'ERITREA', value: 'Eritrea' },
	{ key: 'ESTONIA', value: 'Estonia' },
	{ key: 'ETHIOPIA', value: 'Ethiopia' },
	{ key: 'FIJI', value: 'Fiji' },
	{ key: 'FINLAND', value: 'Finland' },
	{ key: 'FRANCE', value: 'France' },
	{ key: 'GABON', value: 'Gabon' },
	{ key: 'THE_GAMBIA', value: 'The Gambia' },
	{ key: 'GEORGIA', value: 'Georgia' },
	{ key: 'GERMANY', value: 'Germany' },
	{ key: 'GHANA', value: 'Ghana' },
	{ key: 'GREECE', value: 'Greece' },
	{ key: 'GRENADA', value: 'Grenada' },
	{ key: 'GUATEMALA', value: 'Guatemala' },
	{ key: 'GUINEA', value: 'Guinea' },
	{ key: 'GUINEA-BISSAU', value: 'Guinea-Bissau' },
	{ key: 'GUYANA', value: 'Guyana' },
	{ key: 'HAITI', value: 'Haiti' },
	{ key: 'HONDURAS', value: 'Honduras' },
	{ key: 'HUNGARY', value: 'Hungary' },
	{ key: 'ICELAND', value: 'Iceland' },
	{ key: 'INDIA', value: 'India' },
	{ key: 'INDONESIA', value: 'Indonesia' },
	{ key: 'IRAN', value: 'Iran' },
	{ key: 'IRAQ', value: 'Iraq' },
	{ key: 'IRELAND', value: 'Ireland' },
	{ key: 'ISRAEL', value: 'Israel' },
	{ key: 'ITALY', value: 'Italy' },
	{ key: 'JAMAICA', value: 'Jamaica' },
	{ key: 'JAPAN', value: 'Japan' },
	{ key: 'JORDAN', value: 'Jordan' },
	{ key: 'KAZAKHSTAN', value: 'Kazakhstan' },
	{ key: 'KENYA', value: 'Kenya' },
	{ key: 'KIRIBATI', value: 'Kiribati' },
	{ key: 'KOREA,_NORTH', value: 'Korea, North' },
	{ key: 'KOREA,_SOUTH', value: 'Korea, South' },
	{ key: 'KOSOVO', value: 'Kosovo' },
	{ key: 'KUWAIT', value: 'Kuwait' },
	{ key: 'KYRGYZSTAN', value: 'Kyrgyzstan' },
	{ key: 'LAOS', value: 'Laos' },
	{ key: 'LATVIA', value: 'Latvia' },
	{ key: 'LEBANON', value: 'Lebanon' },
	{ key: 'LESOTHO', value: 'Lesotho' },
	{ key: 'LIBERIA', value: 'Liberia' },
	{ key: 'LIBYA', value: 'Libya' },
	{ key: 'LIECHTENSTEIN', value: 'Liechtenstein' },
	{ key: 'LITHUANIA', value: 'Lithuania' },
	{ key: 'LUXEMBOURG', value: 'Luxembourg' },
	{ key: 'MACEDONIA', value: 'Macedonia' },
	{ key: 'MADAGASCAR', value: 'Madagascar' },
	{ key: 'MALAWI', value: 'Malawi' },
	{ key: 'MALAYSIA', value: 'Malaysia' },
	{ key: 'MALDIVES', value: 'Maldives' },
	{ key: 'MALI', value: 'Mali' },
	{ key: 'MALTA', value: 'Malta' },
	{ key: 'MARSHALL_ISLANDS', value: 'Marshall Islands' },
	{ key: 'MAURITANIA', value: 'Mauritania' },
	{ key: 'MAURITIUS', value: 'Mauritius' },
	{ key: 'MEXICO', value: 'Mexico' },
	{ key: 'MICRONESIA,_FEDERATED_STATES_OF', value: 'Micronesia, Federated States of' },
	{ key: 'MOLDOVA', value: 'Moldova' },
	{ key: 'MONACO', value: 'Monaco' },
	{ key: 'MONGOLIA', value: 'Mongolia' },
	{ key: 'MONTENEGRO', value: 'Montenegro' },
	{ key: 'MOROCCO', value: 'Morocco' },
	{ key: 'MOZAMBIQUE', value: 'Mozambique' },
	{ key: 'MYANMAR_(BURMA)', value: 'Myanmar (Burma)' },
	{ key: 'NAMIBIA', value: 'Namibia' },
	{ key: 'NAURU', value: 'Nauru' },
	{ key: 'NEPAL', value: 'Nepal' },
	{ key: 'NETHERLANDS', value: 'Netherlands' },
	{ key: 'NEW_ZEALAND', value: 'New Zealand' },
	{ key: 'NICARAGUA', value: 'Nicaragua' },
	{ key: 'NIGER', value: 'Niger' },
	{ key: 'NIGERIA', value: 'Nigeria' },
	{ key: 'NORWAY', value: 'Norway' },
	{ key: 'OMAN', value: 'Oman' },
	{ key: 'PAKISTAN', value: 'Pakistan' },
	{ key: 'PALAU', value: 'Palau' },
	{ key: 'PANAMA', value: 'Panama' },
	{ key: 'PAPUA_NEW_GUINEA', value: 'Papua New Guinea' },
	{ key: 'PARAGUAY', value: 'Paraguay' },
	{ key: 'PERU', value: 'Peru' },
	{ key: 'PHILIPPINES', value: 'Philippines' },
	{ key: 'POLAND', value: 'Poland' },
	{ key: 'PORTUGAL', value: 'Portugal' },
	{ key: 'QATAR', value: 'Qatar' },
	{ key: 'ROMANIA', value: 'Romania' },
	{ key: 'RUSSIA', value: 'Russia' },
	{ key: 'RWANDA', value: 'Rwanda' },
	{ key: 'SAINT_KITTS_AND_NEVIS', value: 'Saint Kitts and Nevis' },
	{ key: 'SAINT_LUCIA', value: 'Saint Lucia' },
	{ key: 'SAINT_VINCENT_AND_THE_GRENADINES', value: 'Saint Vincent and the Grenadines' },
	{ key: 'SAMOA', value: 'Samoa' },
	{ key: 'SAN_MARINO', value: 'San Marino' },
	{ key: 'SAO_TOME_AND_PRINCIPE', value: 'Sao Tome and Principe' },
	{ key: 'SAUDI_ARABIA', value: 'Saudi Arabia' },
	{ key: 'SENEGAL', value: 'Senegal' },
	{ key: 'SERBIA', value: 'Serbia' },
	{ key: 'SEYCHELLES', value: 'Seychelles' },
	{ key: 'SIERRA_LEONE', value: 'Sierra Leone' },
	{ key: 'SINGAPORE', value: 'Singapore' },
	{ key: 'SLOVAKIA', value: 'Slovakia' },
	{ key: 'SLOVENIA', value: 'Slovenia' },
	{ key: 'SOLOMON_ISLANDS', value: 'Solomon Islands' },
	{ key: 'SOMALIA', value: 'Somalia' },
	{ key: 'SOUTH_AFRICA', value: 'South Africa' },
	{ key: 'SOUTH_SUDAN', value: 'South Sudan' },
	{ key: 'SPAIN', value: 'Spain' },
	{ key: 'SRI_LANKA', value: 'Sri Lanka' },
	{ key: 'SUDAN', value: 'Sudan' },
	{ key: 'SURINAME', value: 'Suriname' },
	{ key: 'SWAZILAND', value: 'Swaziland' },
	{ key: 'SWEDEN', value: 'Sweden' },
	{ key: 'SWITZERLAND', value: 'Switzerland' },
	{ key: 'SYRIA', value: 'Syria' },
	{ key: 'TAIWAN', value: 'Taiwan' },
	{ key: 'TAJIKISTAN', value: 'Tajikistan' },
	{ key: 'TANZANIA', value: 'Tanzania' },
	{ key: 'THAILAND', value: 'Thailand' },
	{ key: 'TOGO', value: 'Togo' },
	{ key: 'TONGA', value: 'Tonga' },
	{ key: 'TRINIDAD_AND_TOBAGO', value: 'Trinidad and Tobago' },
	{ key: 'TUNISIA', value: 'Tunisia' },
	{ key: 'TURKEY', value: 'Turkey' },
	{ key: 'TURKMENISTAN', value: 'Turkmenistan' },
	{ key: 'TUVALU', value: 'Tuvalu' },
	{ key: 'UGANDA', value: 'Uganda' },
	{ key: 'UKRAINE', value: 'Ukraine' },
	{ key: 'UNITED_ARAB_EMIRATES', value: 'United Arab Emirates' },
	{ key: 'UNITED_KINGDOM', value: 'United Kingdom' },
	{ key: 'UNITED_STATES_OF_AMERICA', value: 'United States of America' },
	{ key: 'URUGUAY', value: 'Uruguay' },
	{ key: 'UZBEKISTAN', value: 'Uzbekistan' },
	{ key: 'VANUATU', value: 'Vanuatu' },
	{ key: 'VATICAN_CITY_(HOLY_SEE)', value: 'Vatican City (Holy See)' },
	{ key: 'VENEZUELA', value: 'Venezuela' },
	{ key: 'VIETNAM', value: 'Vietnam' },
	{ key: 'YEMEN', value: 'Yemen' },
	{ key: 'ZAMBIA', value: 'Zambia' },
	{ key: 'ZIMBABWE', value: 'Zimbabwe' }
];
